### ISSUE TITLE
Authenticated Registry Manifest Requests when `checkUpstream` is true

### ISSUE THREAD

**Issue by Budgiebrain994** [indeedeng/harbor-container-webhook#21]
G'day

We're using a private Harbor registry with authentication enabled as a proxy cache. We're using the webhook to rewrite the Docker URLs to point to our private Harbor proxy cache.

All is well if we don't use the `checkUpstream` feature - the images are successfully rewritten and the Kubernetes kubelet successfully pulls the image using our built-in registry credential secret.

However, when `checkUpstream` is set to `true`, the webhook pod looks like it directly calls Harbor, but will receive an Access Denied response because no credentials are attached to the request.

I've looked through the code and I can't see any methods to specify authentication on this `checkUpstream` call.

Are there any discernible paths forward?
Thanks in advance
Lachlan

**Comment by cnmcavoy** [comment]
There isn't any support for checking the upstream manifests with auth.

Potentially it could be added, as a kubernetes secret resource reference that would have to be supplied for each rule. Would something like that solve your use-case?

**Comment by Budgiebrain994** [comment]
Absolutely - that would be an ideal solution and would simplify our workflow.

**Comment by cnmcavoy** [comment]
As of v0.6.0 the config now supports a new field on the rules, `authSecretName`, which if set for a rule, and `checkUpstream` is true, will be used to authenticate the manifests. The image secret referenced must be an image pull secret, (type = `.dockerconfigjson`).

The main limitation is that only 1 auth section is supported in the secret, so if you have image pull secrets with many credentials in the keychain, you will need to split those apart to limit 1 credential in each secret. However, for most Harbor users, creating a system robot account and using that secret as the auth should be all that is required.

**Comment by Budgiebrain994** [comment]
Absolute legend. Thank you!
