### ISSUE TITLE
prometheus config bugs

### ISSUE THREAD

**Issue by disconn3ct** [indeedeng/harbor-container-webhook#25]
Setting `prometheus.enabled` to false is ignored in https://github.com/indeedeng-alpha/harbor-container-webhook/blob/main/deploy/charts/harbor-container-webhook/templates/config.yaml#L16
Setting `prometheus.port` enables it in that file, but does not expose it in https://github.com/indeedeng-alpha/harbor-container-webhook/blob/main/deploy/charts/harbor-container-webhook/templates/deployment.yaml#L51

**Comment by cnmcavoy** [comment]
This should be fixed in v0.6+
