### ISSUE TITLE
Add to awesome list

### ISSUE THREAD

**Issue by Vad1mo** [indeedeng/harbor-container-webhook#30]
This is an awesome project I suggest adding it to https://github.com/container-registry/awesome-harbor

also would be happy to invite you to present it at the harbor community meeting.

**Comment by cnmcavoy** [comment]
I previously presented this at the 11/4/2020 harbor community meeting: https://github.com/goharbor/community/wiki/Harbor-Community-Meetings#1142020

I discussed gifting this project to the maintainers or having them adopt ownership and they went in an alternative direction. But glad you get value out of this project!
