### ISSUE TITLE
Remote error: tls: bad certificate

### ISSUE THREAD

**Issue by babumiriyala** [indeedeng/harbor-container-webhook#31]
Hi there,
seeing the below error.
http: TLS handshake error from 10.1.120.86:39772: remote error: tls: bad certificate

**Comment by babumiriyala** [comment]
this is because of cert-manager deployment was not healthy.

**Comment by cnmcavoy** [comment]
cert-manager questions should be directed towards the cert-manager folks, unless it's specific to this webhook.
